# Generated by Django 5.0.3 on 2024-03-18 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.department",
                verbose_name="部门",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="onboarding_time",
            field=models.DateField(verbose_name="入职时间"),
        ),
    ]
